{% set name = "metalearners" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/metalearners-{{ version }}.tar.gz
  sha256: 3b5b50b2cb512e84c34ff94832eb3bdcdca36f6e9c0e73033297e906d3b02bd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.10
    - scikit-learn >=1.3
    - pandas
    - numpy
    - typing-extensions
    - git_root
    - shap
    - joblib >=1.2.0

test:
  imports:
    - metalearners
    - metalearners.utils
    - metalearners.cross_fit_estimator
    - metalearners.data_generation
    - metalearners.outcome_functions
    - metalearners.tlearner
    - metalearners.slearner
    - metalearners.xlearner
    - metalearners.rlearner
    - metalearners.drlearner
    - metalearners.explainer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/metalearners
  summary: MetaLearners for CATE estimation
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
