{% set name = "metalearners" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/metalearners-{{ version }}.tar.gz
  sha256: bf37b13bec2b21a959bf64bec66e23b852b2a4374cd31f74ba506f19f7fb40c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.10
    - scikit-learn >=1.4
    - pandas
    - numpy
    - typing-extensions
    - shap
    - joblib >=1.2.0

test:
  imports:
    - metalearners
    - metalearners.utils
    - metalearners.cross_fit_estimator
    - metalearners.data_generation
    - metalearners.outcome_functions
    - metalearners.tlearner
    - metalearners.slearner
    - metalearners.xlearner
    - metalearners.rlearner
    - metalearners.drlearner
    - metalearners.explainer
    - metalearners.grid_search
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/metalearners
  summary: MetaLearners for CATE estimation
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
